// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using VehiculosAlquilerApp.Infrastructure.Persistence;

#nullable disable

namespace VehiculoAlquilerAPP.Infrastructure.Persistences.Migrations
{
    [DbContext(typeof(AlquilerDbContext))]
    [Migration("20260519143000_ColoresLicenciaTransito")]
    partial class ColoresLicenciaTransito
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
